feat: update resource-cache KDP
JimBugwadia/KDP pull request #1
Opened 2023-11-21 06:25 UTC by vishal-chdhry

2023-11-22 02:30 UTC, JimBugwadia requested changes
This is shaping up well! Left some comments.

2023-11-22 02:30 UTC, JimBugwadia commented on proposals/resource_cache.md
> +Users can manage which resources to cache by creating a new custom resource called `ContextEntry` provided by Kyverno. This will decouple the creation and usage of a cache entry.
Maybe name as `CachedContextEntry` to be clear on the intent?

2023-11-22 02:30 UTC, JimBugwadia commented on proposals/resource_cache.md
> +2. `External`: An external is an external API call response that should be cached, to create a `ContextEntry` of the external type, The following resource should be created:
`External` may seem to imply the API endpoint is outside the cluster. Can we reuse the name `apiCall` as in a contextEntry?

2023-11-22 02:30 UTC, JimBugwadia commented on proposals/resource_cache.md
> +Kyverno will use Kubernetes dynamic client to create generic informers and listers to cache any Kubernetes resource. These listers will then be stored in the cache and will be accessed when they are
Kyverno will use **a** Kubernetes dynamic client...

2023-11-22 02:30 UTC, JimBugwadia commented on proposals/resource_cache.md
>  ### Failure
Need to specify what happens if either `resource` or `apiCall` fails. Will these be reported as a policy error?

2023-11-22 02:30 UTC, JimBugwadia commented on proposals/resource_cache.md
>  ## Other requirements
We need to clarify when entries will be loaded to the cache, how readiness is handled on startup, if there is any eviction, if there are size limits.

Also will there be any metrics to show cache usage?

2023-11-22 02:30 UTC, JimBugwadia commented on proposals/resource_cache.md
> +    contextEntry:
same as above, rename to `cachedContextEntry`

2023-11-22 02:30 UTC, JimBugwadia commented on proposals/resource_cache.md
> +Users can manage which resources to cache using the same mechanism that is currently used for ConfigMap resources i.e. adding a label `cache.kyverno.io/enabled: "true"` to the resource.
Is this still relevant?

2023-11-22 02:30 UTC, JimBugwadia commented on proposals/resource_cache.md
> +    resourceCache:
update example

2023-11-22 02:30 UTC, JimBugwadia commented on proposals/resource_cache.md
> +1. API calls do not leverage caching by default. If needed, we can add a separate caching mechanism for API calls in the future.
This is covered now, right?

2023-11-22 02:30 UTC, JimBugwadia commented on proposals/resource_cache.md
> +2. Using `cache.kyverno.io/enabled: "true"` can cause issues when users forget to add them to the resource.
do we still require this label?

2023-11-22 02:30 UTC, JimBugwadia commented on proposals/resource_cache.md
> +   1. It is easy to miss a resource when adding the label. `apiCall` will return all the resources of the given type while `resourceCache` will return only those resources that have the label. In the
still relevant?

2023-11-22 02:30 UTC, JimBugwadia commented on proposals/resource_cache.md
> +3. For the use case mentioned in [motivation](#motivation), we need to add a resource to the cache when the policies is applied, otherwise, when the resource is applied for the first time, it will fa
this will be handled if we load the cache during startup

2023-11-22 02:30 UTC, JimBugwadia commented on proposals/resource_cache.md
> +1. We may not be able to use a static Kubernetes client for all types, as the client set can include custom types, and dynamic clients may be resource-intensive. More research is needed to determine
handled...?

2023-11-22 02:30 UTC, JimBugwadia commented on proposals/resource_cache.md
> +2. Typically informers are initialized on startup. This feature may require adding/deleting informers after startup.
handled...?

2023-11-22 14:43 UTC, vishal-chdhry commented on proposals/resource_cache.md
> +3. For the use case mentioned in [motivation](#motivation), we need to add a resource to the cache when the policies is applied, otherwise, when the resource is applied for the first time, it will fa
I took the previous approach and added that to the Alternative section, this is from that section, I left the drawbacks to explain why we did not use this approach

2023-11-22 15:00 UTC, vishal-chdhry commented on proposals/resource_cache.md
> +    resourceCache:
this is the alternatives section

2023-11-22 15:00 UTC, vishal-chdhry commented on proposals/resource_cache.md
> +1. API calls do not leverage caching by default. If needed, we can add a separate caching mechanism for API calls in the future.
this is the alternatives section

2023-12-05 09:30 UTC, realshuting commented on proposals/resource_cache.md
> +This resource allows authors to declare what Kubernetes resource should be cached. The `group` and `version` are optional. If not specified, the preferred versions should be used. An optional `namesp
```suggestion
This resource allows authors to declare what Kubernetes resource should be cached. The `group` and `version` are optional. If not specified, the preferred versions should be used. An optional `namespace` can be used to only cache resources in the namespace, rather than across all namespaces which is the behavior if a namespace is not specified.
```

2023-12-05 09:30 UTC, realshuting commented on proposals/resource_cache.md
> +2. `APICall`: An APICall is an external API call response that should be cached, to create a `CachedContextEntry` of the APICall type, The following resource should be created:
```suggestion
2. `APICall`: An APICall is an external API call response that should be cached, to create a `CachedContextEntry` of the APICall type, the following resource should be created:
```

2023-12-05 09:30 UTC, realshuting commented on proposals/resource_cache.md
> +Users can manage which resources to cache by creating a new custom resource called `CachedContextEntry` provided by Kyverno. This will decouple the creation and usage of a cache entry.
Is `CachedContextEntry` a cluster-wide resource only?

2023-12-05 09:30 UTC, realshuting commented on proposals/resource_cache.md
> +When a `resource` or `apiCall` entry fails, A policy error should be thrown with the error recieved from the cache entry.
```suggestion
When a `resource` or `apiCall` entry fails, a policy error should be thrown with the error received from the cache entry.
```

2023-12-05 09:30 UTC, realshuting commented on proposals/resource_cache.md
>  ### Failure
How does the failure impact the controller status?

2024-01-29 14:05 UTC, vishal-chdhry commented on proposals/resource_cache.md
> +Users can manage which resources to cache by creating a new custom resource called `CachedContextEntry` provided by Kyverno. This will decouple the creation and usage of a cache entry.
yes

2024-01-30 04:30 UTC, JimBugwadia approved these changes

2024-01-30 06:32 UTC, realshuting approved these changes

2024-01-30 06:32 UTC, merged