fix: update resource cache proposal to global context
JimBugwadia/KDP pull request #2
Opened 2024-01-31 15:50 UTC by vishal-chdhry

2024-01-31 16:06 UTC, realshuting reviewed
I have two questions:
1. can a GlobalContextEntry have both `apiCall` and `k8sResource` defined?
2. does one GlobalContextEntry have only one `apiCall` (or `k8sResource`)?

2024-01-31 16:06 UTC, realshuting commented on proposals/resource_cache.md
> +  k8sresource:
```suggestion
  k8sResource:
```

2024-01-31 16:06 UTC, realshuting commented on proposals/resource_cache.md
> +1. `K8sResource`: A resource is a Kubernetes resource that should be prefetched, to create a `GlobalContextEntry` of resource type, the following resource should be created:
```suggestion
1. `k8sResource`: A resource is a Kubernetes resource that should be prefetched, to create a `GlobalContextEntry` of resource type, the following resource should be created:
```

2024-01-31 16:06 UTC, realshuting commented on proposals/resource_cache.md
> +2. `APICall`: An APICall is an external API call response that should be prefetched, to create a `GlobalContextEntry` of the APICall type, the following resource should be created:
```suggestion
2. `apiCall`: An APICall is an external API call response that should be prefetched, to create a `GlobalContextEntry` of the APICall type, the following resource should be created:
```

2024-01-31 16:09 UTC, vishal-chdhry commented
@realshuting 
> can a GlobalContextEntry have both apiCall and k8sResource defined?

One entry can only have either 1 apiCall or 1 k8sResource
> does one GlobalContextEntry have only one apiCall (or k8sResource)?

Yes one entry can have only one API call or k8sResource

2024-01-31 16:11 UTC, realshuting commented
> @realshuting
> 
> > can a GlobalContextEntry have both apiCall and k8sResource defined?
> 
> One entry can only have either 1 apiCall or 1 k8sResource
> 
> > does one GlobalContextEntry have only one apiCall (or k8sResource)?
> 
> Yes one entry can have only one API call or k8sResource

Can we clarify it in KDP?

2024-01-31 16:16 UTC, vishal-chdhry commented
@realshuting Updated!

2024-01-31 16:17 UTC, realshuting approved these changes

2024-02-01 03:12 UTC, JimBugwadia requested changes

2024-02-01 03:12 UTC, JimBugwadia commented on proposals/resource_cache.md
> +- Name: Prefetched Global Context Entry
Just call it `Global Context Entry`

2024-02-01 03:12 UTC, JimBugwadia commented on proposals/resource_cache.md
>  - Author(s): @JimBugwadia
Please add yourself

2024-02-01 03:12 UTC, JimBugwadia commented on proposals/resource_cache.md
> +2. Allow policy rules to reference global context data
```suggestion
2. Allow policy rules to reference global context data.

The global context is populated when Kyverno is started, and can be referenced by multiple policy rules. Kubernetes resource data, fetched from the API server is automatically updated based on events. Data fetched from other sources can be periodically updated.
```

2024-02-01 03:12 UTC, JimBugwadia commented on proposals/resource_cache.md
> +1. Allow users to manage which resources should be prefetched
```suggestion
1. Allow users to manage what data should be loaded in a global context.
```

2024-02-01 03:12 UTC, JimBugwadia commented on proposals/resource_cache.md
> +1. `k8sResource`: A resource is a Kubernetes resource that should be prefetched, to create a `GlobalContextEntry` of resource type, the following resource should be created:
lets call this `kubernetesResource` or `resource`.

2024-02-01 03:12 UTC, JimBugwadia commented on proposals/resource_cache.md
> +  k8sResource:
Lets call this `kubernetesResource` or `resource`.

2024-02-01 03:12 UTC, JimBugwadia commented on proposals/resource_cache.md
> +Global context will require an in-memory store that will be stored in every controller. We will store both types of context entries as follows:
```suggestion
The global context uses an in-memory store in each controller instance. We will store both types of context entries as follows:
```

2024-02-01 03:22 UTC, JimBugwadia commented on proposals/resource_cache.md
> +The global context is populated when Kyverno is started, and can be referenced by multiple policy rules. Kubernetes resource data, fetched from the API server is automatically updated based on events
```suggestion
The global context is populated when Kyverno runs, and can then be referenced by multiple policy rules. Kubernetes resource data, fetched from the API server is automatically updated based on events. Data fetched from other sources can be periodically updated.
```

2024-02-01 03:24 UTC, JimBugwadia approved these changes

2024-02-01 03:24 UTC, merged